repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true

      - id: black
        name: Black
        entry: poetry run black .
        language: system
        types: [python]
        require_serial: true

      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
        require_serial: true
