name: Lint

on:
    push:
        paths:
            - src/**
    pull_request:
        paths:
            - src/**

defaults:
    run:
        working-directory: src

jobs:
    flake&:
        runs-on: ubuntu-latest
        name: flake8
        steps:
            - name: Checkout Repository
              uses: actions/setup-python@v2.2.2
              with:
                  python-version: "3.9"

            - name: Setup Poetry
              run: python -m pip install -U poetry

            - name: Install Dependencies
              run: poetry install

            - name: Run flake8
              run: poetry run flake8
    black:
        runs-on: ubuntu-latest
        name: Black
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Python Environment
              uses: actions/setup-python@v2.2.2
              with:
                  python-version: "3.9"

            - name: Setup Poetry
              run: python -m pip install -U poetry

            - name: Install Dependencies
              run: poetry install

            - name: Black
              run: poetry run black --check src/
