name: Test

on:
    push:
        paths:
            - src/**
    pull_request:
        paths:
            - src/**

defaults:
    run:
        working-directory: src

jobs:
    test:
        runs-on: ubuntu-latest
        name: pytest
        steps:
            - name: Checkout Repository
              uses: actions/setup-python@v2.2.2
              with:
                  python-version: "3.9"

            - name: Setup Poetry
              run: python -m pip install -U poetry

            - name: Install Dependencies
              run: poetry install

            - name: Run pytest
              run: pytest
